stacks_dir: stacks
# Only if you want to override 
# cron:
#   profile: cron
http:
  # then per stack we should be able to use the following var
  # $STACKR_PROV_DOMAIN => [stackname].localhost
  # the user has the ability to do custom.[stackname].localhost if multiple are needed
  base_domain: localhost
paths:
  # all of these are to be checked that they are actual folders which exist
  
  backup_dir: ./backups

  pools:
    # So this will provision paths per stack which requires it
    # $STACKR_PROV_POOL_SSD => .vols_ssd/stack_volumes/[stackname]
    SSD: .vols_ssd/stack_volumes
    # $STACKR_PROV_POOL_HDD => .vols_hdd/stack_volumes/[stackname]
    HDD: .vols_hdd/stack_volumes

  custom:
    # This should be a custom path var
    # $STACKR_PATH_MEDIA => .vols_hdd/Media
    MEDIA: .vols_hdd/Media

# this is for any extra non secret vars we might want 
# theres global for every stack and stacks which will be scoped to said stack
env:
  global:
    TEST_VAR: test_value 
  stacks:
    owncloud:
      TRUSTED_DOMAINS: 192.168.1.100,oc.dumitruvulpe.com


