services:
  teamspeak:
    image: teamspeak:latest
    container_name: teamspeak
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 9987:9987/udp
      - 10011:10011/tcp
      - 30033:30033/tcp
    environment:
      - TS3SERVER_LICENSE=accept
      - TS3SERVER_DB_PLUGIN=ts3db_mariadb
      - TS3SERVER_DB_SQLCREATEPATH=create_mariadb
      - TS3SERVER_DB_HOST=db
      - TS3SERVER_DB_USER=${TEAMSPEAK_DB_USER}
      - TS3SERVER_DB_PASSWORD=${TEAMSPEAK_DB_PASSWORD}
      - TS3SERVER_DB_NAME=${TEAMSPEAK_DB_NAME}
      - TS3SERVER_DB_WAITUNTILREADY=30
    volumes:
      - ${STACKR_PROV_POOL_SSD}/data:/var/ts3server

  db:
    image: mariadb:11
    container_name: teamspeak-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${TEAMSPEAK_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${TEAMSPEAK_DB_NAME}
      - MYSQL_USER=${TEAMSPEAK_DB_USER}
      - MYSQL_PASSWORD=${TEAMSPEAK_DB_PASSWORD}
    volumes:
      - ${STACKR_PROV_POOL_SSD}/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
