services:
  npm:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ${POD_STORAGE_SSD}/data:/data
      - ${POD_STORAGE_SSD}/letsencrypt:/etc/letsencrypt
