services:
  npm:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ${STACK_STORAGE_SSD}/data:/data
      - ${STACK_STORAGE_SSD}/letsencrypt:/etc/letsencrypt
      - ./data/nginx/custom/stream.conf:/data/nginx/custom/stream.conf
      - ./data/nginx/custom/http.conf:/data/nginx/custom/http.conf
