{
 "title": "Stackr: Media",
 "refresh": "30s",
 "panels": [
  { "title": "jellyfin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "jellyfin Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_start_time_seconds{name=\"jellyfin\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"jellyfin\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=\"jellyfin\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"jellyfin\"}[5m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=\"jellyfin\"}[5m]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=\"jellyfin\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=\"jellyfin\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(time() - container_start_time_seconds{name=\"jellyfin\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(changes(container_start_time_seconds{name=\"jellyfin\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"jellyfin\",detected_level=\"error\"} [$__range])) or vector(0)"
    }
   ]
  },
  { "title": "prowlarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "prowlarr Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_start_time_seconds{name=\"prowlarr\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"prowlarr\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=\"prowlarr\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"prowlarr\"}[5m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=\"prowlarr\"}[5m]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=\"prowlarr\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=\"prowlarr\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(time() - container_start_time_seconds{name=\"prowlarr\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(changes(container_start_time_seconds{name=\"prowlarr\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"prowlarr\",detected_level=\"error\"} [$__range])) or vector(0)"
    }
   ]
  },
  { "title": "sonarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "sonarr Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_start_time_seconds{name=\"sonarr\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"sonarr\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=\"sonarr\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"sonarr\"}[5m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=\"sonarr\"}[5m]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=\"sonarr\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=\"sonarr\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(time() - container_start_time_seconds{name=\"sonarr\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(changes(container_start_time_seconds{name=\"sonarr\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"sonarr\",detected_level=\"error\"} [$__range])) or vector(0)"
    }
   ]
  },
  { "title": "radarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "radarr Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_start_time_seconds{name=\"radarr\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"radarr\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=\"radarr\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"radarr\"}[5m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=\"radarr\"}[5m]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=\"radarr\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=\"radarr\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(time() - container_start_time_seconds{name=\"radarr\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(changes(container_start_time_seconds{name=\"radarr\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"radarr\",detected_level=\"error\"} [$__range])) or vector(0)"
    }
   ]
  },
  { "title": "bazarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "bazarr Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_start_time_seconds{name=\"bazarr\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"bazarr\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=\"bazarr\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"bazarr\"}[5m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=\"bazarr\"}[5m]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=\"bazarr\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=\"bazarr\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(time() - container_start_time_seconds{name=\"bazarr\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(changes(container_start_time_seconds{name=\"bazarr\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"bazarr\",detected_level=\"error\"} [$__range])) or vector(0)"
    }
   ]
  },
  { "title": "flaresolverr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "flaresolverr Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_start_time_seconds{name=\"flaresolverr\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"flaresolverr\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=\"flaresolverr\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"flaresolverr\"}[5m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=\"flaresolverr\"}[5m]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=\"flaresolverr\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=\"flaresolverr\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(time() - container_start_time_seconds{name=\"flaresolverr\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(changes(container_start_time_seconds{name=\"flaresolverr\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"flaresolverr\",detected_level=\"error\"} [$__range])) or vector(0)"
    }
   ]
  },
  { "title": "rdt-client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "rdt-client Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_start_time_seconds{name=\"rdt-client\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"rdt-client\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=\"rdt-client\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"rdt-client\"}[5m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=\"rdt-client\"}[5m]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=\"rdt-client\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=\"rdt-client\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(time() - container_start_time_seconds{name=\"rdt-client\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(changes(container_start_time_seconds{name=\"rdt-client\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"rdt-client\",detected_level=\"error\"} [$__range])) or vector(0)"
    }
   ]
  },
  { "title": "zilean-postgres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "zilean-postgres Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_start_time_seconds{name=\"zilean-postgres\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"zilean-postgres\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=\"zilean-postgres\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"zilean-postgres\"}[5m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=\"zilean-postgres\"}[5m]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=\"zilean-postgres\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=\"zilean-postgres\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(time() - container_start_time_seconds{name=\"zilean-postgres\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(changes(container_start_time_seconds{name=\"zilean-postgres\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"zilean-postgres\",detected_level=\"error\"} [$__range])) or vector(0)"
    }
   ]
  },
  { "title": "zilean", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "zilean Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_start_time_seconds{name=\"zilean\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"zilean\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=\"zilean\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"zilean\"}[5m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=\"zilean\"}[5m]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=\"zilean\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=\"zilean\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(time() - container_start_time_seconds{name=\"zilean\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(changes(container_start_time_seconds{name=\"zilean\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"zilean\",detected_level=\"error\"} [$__range])) or vector(0)"
    }
   ]
  },
  { "title": "configarr-init", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "configarr-init Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_start_time_seconds{name=\"configarr-init\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"configarr-init\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=\"configarr-init\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"configarr-init\"}[5m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=\"configarr-init\"}[5m]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=\"configarr-init\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=\"configarr-init\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(time() - container_start_time_seconds{name=\"configarr-init\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(changes(container_start_time_seconds{name=\"configarr-init\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"configarr-init\",detected_level=\"error\"} [$__range])) or vector(0)"
    }
   ]
  },
  { "title": "configarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "configarr Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_start_time_seconds{name=\"configarr\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"configarr\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=\"configarr\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"configarr\"}[5m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=\"configarr\"}[5m]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=\"configarr\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=\"configarr\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(time() - container_start_time_seconds{name=\"configarr\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(changes(container_start_time_seconds{name=\"configarr\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"configarr\",detected_level=\"error\"} [$__range])) or vector(0)"
    }
   ]
  },
  { "title": "media-bootstrap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "media-bootstrap Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_start_time_seconds{name=\"media-bootstrap\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"media-bootstrap\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=\"media-bootstrap\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"media-bootstrap\"}[5m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=\"media-bootstrap\"}[5m]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=\"media-bootstrap\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=\"media-bootstrap\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(time() - container_start_time_seconds{name=\"media-bootstrap\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(changes(container_start_time_seconds{name=\"media-bootstrap\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"media-bootstrap\",detected_level=\"error\"} [$__range])) or vector(0)"
    }
   ]
  }
 ]
}