{
 "title": "Stackr: Nextcloud",
 "refresh": "30s",
 "panels": [
  {
   "title": "nextcloud Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_start_time_seconds{name=\"nextcloud\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"nextcloud\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=\"nextcloud\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"nextcloud\"}[5m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=\"nextcloud\"}[5m]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=\"nextcloud\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=\"nextcloud\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(time() - container_start_time_seconds{name=\"nextcloud\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(changes(container_start_time_seconds{name=\"nextcloud\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"nextcloud\",detected_level=\"error\"} [$__range])) or vector(0)"
    }
   ]
  },
  {
   "title": "nextcloud_db Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_start_time_seconds{name=\"nextcloud_db\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"nextcloud_db\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=\"nextcloud_db\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"nextcloud_db\"}[5m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=\"nextcloud_db\"}[5m]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=\"nextcloud_db\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=\"nextcloud_db\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(time() - container_start_time_seconds{name=\"nextcloud_db\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(changes(container_start_time_seconds{name=\"nextcloud_db\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"nextcloud_db\",detected_level=\"error\"} [$__range])) or vector(0)"
    }
   ]
  },
  {
   "title": "nextcloud_redis Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_start_time_seconds{name=\"nextcloud_redis\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"nextcloud_redis\"}[5m])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=\"nextcloud_redis\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"nextcloud_redis\"}[5m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=\"nextcloud_redis\"}[5m]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=\"nextcloud_redis\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=\"nextcloud_redis\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(time() - container_start_time_seconds{name=\"nextcloud_redis\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(changes(container_start_time_seconds{name=\"nextcloud_redis\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"nextcloud_redis\",detected_level=\"error\"} [$__range])) or vector(0)"
    }
   ]
  }
 ]
}